### PR TITLE
Hotfix temperature conversion

### PR DESCRIPTION
**Pull request by CamAnNguyen**

### CODE REVIEW

**Comment by Sergeykot** [comment]
TODO: regexp `/^[\-|\d]\d*\.{0,1}\d{0,2}$/`
should be in one place (maybe Functions.js)
but

it is hotfix so we accept it..

**Comment by Sergeykot** [comment]
:+1:

**Comment by CamAnNguyen** [comment]
Agree! I will put js regex in one place. Do you have any suggestion about ruby regex? How can we keep both ruby and js in one place ?

**Comment by Sergeykot** [comment]
we can make some settings with and get them JSON request.
but at least regexp should be in 1 place on backend

**Comment by Sergeykot** [comment]
and on frontend

**Comment by Sergeykot** [comment]
UPD: ideally such settings that have to be handled both on server and front-end are handled with something like `Settings` gem and served in .js with help of .erb

**Comment by CamAnNguyen** [comment]
Thank for your suggestion. Currently, we have many of these settings in Sample and Reaction model in both front-end and back-end.

**Pull request merged**
