### PR TITLE
Add select all option for device inbox folder

### PR DESCRIPTION
**Pull request by f-idiris**
- Fixed the attachments checkboxes not updating when clicked issue. 
[device_checkbox_not_working.webm](https://github.com/ComPlat/chemotion_ELN/assets/112618970/1d03c95a-c8df-4167-bc05-83f5d33d7ab0)

- Added a select all datasets checkbox. 

[checkboxes_fixed_and_select_all_feat.webm](https://github.com/ComPlat/chemotion_ELN/assets/112618970/c3cf42f0-dde5-40cc-b483-acd795c70334)

### CODE REVIEW

**Review by endevor-music — APPROVED** [review]
Looks good to me.

**Comment by endevor-music** [comment]
@PiTrem ready to merge (unsure via squash or rebase, so I'll leave it to you.)

**Review by endevor-music — DISMISSED** [review]

**Comment by endevor-music** [comment]
Hi @f-idiris, could you provide a quick image / video in the pR description of the bug fix please?

**Review by endevor-music — APPROVED** [review]
LGTM.

**Review by PiTrem — APPROVED** [review]

**Pull request merged**
