### PR TITLE
Add editor to Reaction description

### PR DESCRIPTION
**Pull request by CamAnNguyen**
- Add Quill editor to Reaction description
- Reaction is updated when user finish typing (after 300ms)
- Report use raw text, not the formatted description
- Resolves #680

### CODE REVIEW

**Comment by Sergeykot** [comment]
> Reaction is updated when user finish typing (after 300ms)

not work for me unless I press 'Save'

**Comment by CamAnNguyen** [comment]
> Reaction is updated when user finish typing (after 300ms)

With this line, I mean that reaction is updated (considered as changed, display floppy, broadcast description changes to other components) only when the user finishes typing. It doesn't save to the DB when the user hasn't pressed "Save"

Sorry for this vague explanation

**Comment by PiTrem** [comment]
:+1:

**Comment by PiTrem** [comment]
:+1:

**Pull request merged**
