### PR TITLE
Report can have samples and reactions

### PR DESCRIPTION
**Pull request by JasonYCHuang**
Users can add samples & reactions to Report.

### CODE REVIEW

**Comment by Sergeykot** [comment]
1 change needed

**Comment by JasonYCHuang** [comment]
Will rebase this base on PR#324.

**Comment by JasonYCHuang** [comment]
Deploy to the test server.
Wait for Nicole's review.

**Comment by Sergeykot** [comment]
branch rebase from master

**Comment by Sergeykot** [comment]
deployed to test server

**Pull request merged**
