### PR TITLE
Compact scheme

### LINKED ISSUE #449: Improve reference/literature assignment
no bug, only desired improvement: currently, there are two options that can be used as additional information for literature/references (cited by/referring to). The terms should be modified as it is not clear how to use them without further clarification.

### PR DESCRIPTION
**Pull request by PiTrem**
resolve #449

### CODE REVIEW

**Comment by Sergeykot** [comment]
:+1:

**Comment by PiTrem** [comment]
on hold

**Comment by PiTrem** [comment]
updated

**Comment by JasonYCHuang** [comment]
👍

**Pull request merged**
