### PR TITLE
780 enhencing versioning feature

### PR DESCRIPTION
**Pull request by Allenskywalker92**
- [ ] rather 1-story 1-commit than sub-atomic commits

- [ ] commit title is meaningful =>  git history search

- [ ] commit description is helpful => helps the reviewer to understand the changes

- [ ] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [ ] added code is linted

- [ ] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [ ] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [ ] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [ ] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

### CODE REVIEW

**Comment by Allenskywalker92** [comment]
[Uploading screen-capture (1).webm…]()

**Comment by adambasha0** [comment]
Review Comment: on commit (Refactorings for ReactionDetails and SampleDetails):
1- Apparently you have changed the structure of the analyses tab, by having sub-analysis tabs inside it for each reaction product. it seems like there is still an additional tab (maybe it is the original old one) for all products, do we still need it? . can you check the video and verify? @mschneider85 
Thank you 

https://user-images.githubusercontent.com/55552142/182336385-2f3ed66e-30fa-4771-a4d4-f143775f38b7.mp4

**Comment by mschneider85** [comment]
@Allenskywalker92 I had a notification/mention about this PR that I can no longer find. Has the problem been resolved in the meantime?

**Comment by Allenskywalker92** [comment]
@mschneider85 I don't know either. Couldn't find any comment.

**Comment by adambasha0** [comment]
Revert function in the histroy tab of reactions does not work. Also name field in history is empty if the sample has no name. I think maybe it would be better to have common name of any other type of sample identification, so that user can have an idea which sample is this? - or what do you think?

https://user-images.githubusercontent.com/55552142/185579466-9b46d84e-9c10-4077-b214-4fa801668a02.mp4

**Comment by adambasha0** [comment]
> mschneider85

Hello Martin, I put some comments here. I would be thankful if you can check these :)

**Comment by PiTrem** [comment]
moved to https://github.com/ComPlat/chemotion_ELN/pull/1253

**Pull request closed without merging**
