### PR TITLE
export docx research plan error

### PR DESCRIPTION
**Pull request by mehreenmansur**
Fix of exporting a reasearch plan to docx sometimes not working [#902 ](https://github.com/ComPlat/chemotion_ELN/issues/902
[Screencast from 20.11.2022 12:56:42.webm](https://user-images.githubusercontent.com/26220177/203984625-47b01411-8b66-4960-9f14-5884715e9bf1.webm)
)

### CODE REVIEW

**Comment by adambasha0** [comment]
Hi Mehreen, currently I am having this error in frontend, it is not related to your fix. But It seems the main branch has more issues now with research plan functions. 

https://user-images.githubusercontent.com/55552142/205306373-816508a9-1f30-4bd7-a726-3c4b7b96bd5a.mp4

**Review by adambasha0 — CHANGES_REQUESTED** [review]
Currently, can not check the fix you applied, because there is another error in the front end not related to your fix preventing me from saving and exporting the research plan. also, the branch is 8 commits behind the main branch. 

Actions required: 
1- update the branch to be up-to-date with main.
2- check again if the frontend bug still persists.
3- The reported error from the user currently can not be verified using complat-server (error is not reproducible). Therefore, requested (data, preferably the same data used to report the error) from the user to check again.

**Comment by mehreenmansur** [comment]
> Hi @mehreenmansur Mehreen, currently I am having this error in frontend, it is not related to your fix. But It seems the main branch has more issues now with research plan functions.
> research_plan_error.mp4

The video file cannot be played. it is corrupt.

**Comment by adambasha0** [comment]
> > Hi @mehreenmansur Mehreen, currently I am having this error in frontend, it is not related to your fix. But It seems the main branch has more issues now with research plan functions.
> > research_plan_error.mp4
> 
> The video file cannot be played. it is corrupt.

it works for me, will send it on discord again

**Review by PiTrem — APPROVED** [review]

**Pull request merged**
