### PR TITLE
CI: use Pronto linting without 3rd party action

### PR DESCRIPTION
**Pull request by JanCBrammer**
Enables more control over Pronto configuration (e.g., Ruby version), and removes dependency on 3rd party action.

### CODE REVIEW

**Review by matt-hh — CHANGES_REQUESTED** [review]
Hi @JanCBrammer 

i fetched your branch inside our fork and created a PR against your ci-linting branch.

Pronto stops with an error:
```
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/pronto-0.11.0/lib/pronto/git/repository.rb:87:in `merge_base': object not found - no match for id
```

Line 87 is here https://github.com/prontolabs/pronto/blob/v0.11.0/lib/pronto/git/repository.rb#L87

Found this issue: https://github.com/prontolabs/pronto/issues/404 but nothing works.
Found another issue https://github.com/prontolabs/pronto/issues/392 and it seems `--unshallow` is a solution?!

But now there are new problems. It looks like rubocop is crashing but pronto returns green and tests are started?!!? See here https://github.com/ComPlat/chemotion_ELN/actions/runs/3371925656/jobs/5594748548

Output is not very helpful. Any ideas??
```
Run pronto run -f text -c origin/ci-linting
  pronto run -f text -c origin/ci-linting
  shell: /usr/bin/bash -e {0}
  env:
    PRONTO_PULL_REQUEST_ID: 1007
To use retry middleware with Faraday v[2](https://github.com/ComPlat/chemotion_ELN/actions/runs/3371925656/jobs/5594748548#step:7:2).0+, install `faraday-retry` gem
An error occurred while Lint/MissingCopEnableDirective cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb.
To see the complete backtrace run rubocop -d.
An error occurred while Lint/RedundantCopEnableDirective cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb.
To see the complete backtrace run rubocop -d.
An error occurred while Rails/RootPublicPath cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:6:20.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/EmptyLineAfterFinalLet cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:24:2.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/MultipleMemoizedHelpers cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:24:2.
To see the complete backtrace run rubocop -d.
An error occurred while Style/BlockDelimiters cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:25:4.
To see the complete backtrace run rubocop -d.
An error occurred while Style/TrailingCommaInArrayLiteral cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:26:6.
To see the complete backtrace run rubocop -d.
An error occurred while Rails/Pluck cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:4[3](https://github.com/ComPlat/chemotion_ELN/actions/runs/3371925656/jobs/5594748548#step:7:3):28.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/MultipleExpectations cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:[4](https://github.com/ComPlat/chemotion_ELN/actions/runs/3371925656/jobs/5594748548#step:7:4)7:4.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/BeEq cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:[5](https://github.com/ComPlat/chemotion_ELN/actions/runs/3371925656/jobs/5594748548#step:7:5)1:33.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/BeEq cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:52:53.
To see the complete backtrace run rubocop -d.
An error occurred while RSpec/BeEq cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:53:33.
To see the complete backtrace run rubocop -d.
An error occurred while Lint/ParenthesesAsGroupedExpression cop was inspecting /home/runner/work/chemotion_ELN/chemotion_ELN/spec/usecases/research_plans/import_table_from_spreadsheet_spec.rb:5[6](https://github.com/ComPlat/chemotion_ELN/actions/runs/3371925656/jobs/5594748548#step:7:7):41.
To see the complete backtrace run rubocop -d.

```

**Comment by JanCBrammer** [comment]
> It looks like rubocop is crashing but pronto returns green and tests are started?!!?

That should be fixed with 8fb529f.

**Comment by JanCBrammer** [comment]
> Output is not very helpful. Any ideas??

That's indeed not much to go on... maybe 3107cae? Before 3107cae the Ruby versions in `.rubocop.yml` (2.6.6.) and the pronto action (2.7.6) didn't match, which might cause conflicts in the conventions that RuboCop is trying to enforce?

**Comment by JanCBrammer** [comment]
> Output is not very helpful. Any ideas??

The `rubocop` gem looks like the most probable culprit.

This is the installation log from run https://github.com/ComPlat/chemotion_ELN/actions/runs/3361234648/jobs/5571378310, where the pronto action still worked:
```
Successfully installed mime-types-data-3.2022.0105
Successfully installed mime-types-3.4.1
Successfully installed multi_xml-0.6.0
When you HTTParty, you must party hard!
Successfully installed httparty-0.20.0
Successfully installed unicode-display_width-2.3.0
Successfully installed terminal-table-3.0.2
Successfully installed gitlab-4.19.0
Successfully installed faraday-net_http-3.0.1
Successfully installed ruby2_keywords-0.0.5
Successfully installed faraday-2.6.0
Successfully installed public_suffix-5.0.0
Successfully installed addressable-2.8.1
Successfully installed sawyer-0.9.2
Successfully installed octokit-4.25.1
Successfully installed rainbow-3.1.1
Building native extensions. This could take a while...
Successfully installed rugged-1.0.1
Successfully installed thor-1.2.1
Successfully installed pronto-0.11.0
Successfully installed rexml-3.2.5
Successfully installed parallel-1.22.1
Successfully installed ast-2.4.2
Successfully installed parser-3.1.2.1
Successfully installed regexp_parser-2.6.0
Successfully installed rubocop-ast-1.23.0
Successfully installed ruby-progressbar-1.11.0
Successfully installed rubocop-1.37.1
Successfully installed pronto-rubocop-0.11.2
Successfully installed rubocop-rspec-2.14.2
Successfully installed concurrent-ruby-1.1.10
Successfully installed i18n-1.12.0
Successfully installed tzinfo-2.0.5
Successfully installed activesupport-7.0.4
Successfully installed rack-3.0.0
Successfully installed rubocop-rails-2.17.2
Successfully installed rubocop-performance-1.15.0
35 gems installed
```

And here's the installation log from run https://github.com/ComPlat/chemotion_ELN/actions/runs/3375754066/jobs/5602698308, where the pronto action is broken:
```
Successfully installed mime-types-data-3.2022.0105
Successfully installed mime-types-3.4.1
Successfully installed multi_xml-0.6.0
When you HTTParty, you must party hard!
Successfully installed httparty-0.20.0
Successfully installed unicode-display_width-2.3.0
Successfully installed terminal-table-3.0.2
Successfully installed gitlab-4.19.0
Successfully installed faraday-net_http-3.0.1
Successfully installed ruby2_keywords-0.0.5
Successfully installed faraday-2.6.0
Successfully installed public_suffix-5.0.0
Successfully installed addressable-2.8.1
Successfully installed sawyer-0.9.2
Successfully installed octokit-4.25.1
Successfully installed rainbow-3.1.1
Building native extensions. This could take a while...
Successfully installed rugged-1.0.1
Successfully installed thor-1.2.1
Successfully installed pronto-0.11.0
Successfully installed rexml-3.2.5
Successfully installed parallel-1.22.1
Successfully installed ast-2.4.2
Successfully installed parser-3.1.2.1
Successfully installed regexp_parser-2.6.0
Successfully installed rubocop-ast-1.23.0
Successfully installed ruby-progressbar-1.11.0
Successfully installed rubocop-1.38.0
Successfully installed pronto-rubocop-0.11.2
Successfully installed rubocop-rspec-2.14.2
Successfully installed concurrent-ruby-1.1.10
Successfully installed i18n-1.12.0
Successfully installed tzinfo-2.0.5
Successfully installed activesupport-7.0.4
Successfully installed rack-3.0.0
Successfully installed rubocop-rails-2.17.2
Successfully installed rubocop-performance-1.15.0
35 gems installed
```

The only difference as far as I can tell is the `rubocop` version. Version 1.38.0 was released yesterday: https://github.com/rubocop/rubocop/releases.

**Review by matt-hh — APPROVED** [review]
LGTM

**Review by PiTrem — APPROVED** [review]

**Pull request merged**
