### PR TITLE
fix cannot open chemspectra in research plan and reaction

### PR DESCRIPTION
**Pull request by baolanlequang**
- [x] rather 1-story 1-commit than sub-atomic commits

- [x] commit title is meaningful =>  git history search

- [x] commit description is helpful => helps the reviewer to understand the changes

- [x] code is up-to-date with the latest developments of the target branch (rebased to it or whatever) => :fast_forward:-merge for linear history is favoured

- [x] added code is linted

- [x] tests are passing (at least locally): we still have some random test failure on CI. thinking of asking spec/examples.txt to be commited

- [x] in case the changes are visible to the end-user,  video or screenshots should be added to the PR => helps  with user testing

- [ ] testing coverage improvement is improved.

- [x] CHANGELOG :  add a bullet point on top (optional: reference to github issue/PR )

- [x] parallele PR for documentation  on docusaurus  if the feature/fix is tagged for a release

### CODE REVIEW

**Comment by jhmegorei** [comment]
Can you please update the ViewSpectra component by renaming the "sample" prop to something that makes it more clear that also ResearchPlans or Reactions can be passed?

Currently the property is named sample but the ResearchPlanDetailsContainers.js and ReactionDetailsContainers.js pass something that is not a sample, which is confusing.

**Review by jhmegorei — CHANGES_REQUESTED** [review]
Can you please update the ViewSpectra component by renaming the "sample" prop to something that makes it more clear that also ResearchPlans or Reactions can be passed?

Currently the property is named sample but the ResearchPlanDetailsContainers.js and ReactionDetailsContainers.js pass something that is not a sample, which is confusing.

**Comment by baolanlequang** [comment]
For now, we should keep it first because this pull request needs to be merged for the next release. It is a critical bug.

For the changing name, I think you can open another issue for that.

**Review by PiTrem — CHANGES_REQUESTED** [review]
DRY

identical routines , that also appears in ../Sample.js if I am not mistaken

**Review by PiTrem — APPROVED** [review]

**Pull request merged**
