### PR TITLE
Make Reaction temperature a time series

### LINKED ISSUE #550: Include data from custom generic  segments into the PDF/Word file export
We have started using the generic segments functionality which has been really useful. However, we found that the data is not actually exported in the Word/PDF files, at least not by default in v0.9.1 of Chemotion. Has this already been implemented by any chance in a newer version? If not, would it be possible to implement this to have this data also exported?

### PR DESCRIPTION
**Pull request by CamAnNguyen**
- Change Reaction temperature field to a Hash with default format as follow:
{
  "valueUnit" => "C",
  "data" => [
    {"time" => "00:00:00", "value" => 21}
  ]
}
- Add a temperature chart based on temperature field
- User still can input a static temperature field
- Add a temperature table to edit new temperature field
- Resolves #550, #551

### CODE REVIEW

**Comment by Sergeykot** [comment]
does not work fine for me in Chrome/Ubuntu

**Comment by Sergeykot** [comment]
any news? :smile:

**Comment by CamAnNguyen** [comment]
It has been ready since yesterday

**Comment by Sergeykot** [comment]
sorry missed the update, please write directly to PR just in case..

**Comment by Sergeykot** [comment]
I can add a temperature point with no "temperature" value..

**Comment by Sergeykot** [comment]
@CamAnNguyen @camannguyenthanh

**Comment by CamAnNguyen** [comment]
Update to have default value for Temperature (21) and Time ("00:00:00")

**Comment by Sergeykot** [comment]
This has been updated? I see migration changed :)

**Pull request closed without merging**
