### PR TITLE
checkbox out of order in menu bar

### PR DESCRIPTION
**Pull request by mehreenmansur**
Checkbox is out of order [#953](https://github.com/ComPlat/chemotion_ELN/issues/953)
checkbox-out-of-order

### CODE REVIEW

**Comment by mehreenmansur** [comment]
@JanCBrammer I could generate this issue in `main branch` and thus solved it against main.

**Comment by endevor-music** [comment]
> @mehreenmansur, @endevor-music, just to make sure I'm understanding the situation correctly.
> 
> This PR fixes a problem that's not yet occurring on `main`, right?
> 
> I.e., this PR fixes a problem that would occur once #732 is merged?

Yes, you're correct - #732 was merged for v1.4, which has since been backported to main, but the PR was never resolved/closed.

**Comment by JanCBrammer** [comment]
@endevor-music, 
it doesn't seem that the changes from #732 are in `main` yet.
Looks like the file that's been changed in #732 has been moved on `main` and the changes aren't applied yet:
https://github.com/ComPlat/chemotion_ELN/blob/93697f0b37cd94d7236cf1c9fb11664a037061cd/app/packs/src/apps/mydb/elements/Elements.js#L39-L46

**Comment by JanCBrammer** [comment]
@endevor-music, can you rebase #732 onto the latest `main` (@PiTrem already switched the base branch from `development-5` to `main`, thanks!) and apply the change to the file at the new location (`app/packs/src/apps/mydb/elements/Elements.js`)?

**Comment by endevor-music** [comment]
> @endevor-music, can you rebase #732 onto the latest `main` (@PiTrem already switched the base branch from `development-5` to `main`, thanks!) and apply the change to the file at the new location (`app/packs/src/apps/mydb/elements/Elements.js`)?

Sure, I'll do this in the afternoon. :)

**Comment by adambasha0** [comment]
Issue is identified is the main branch, the fix added solve the issue. Therefor safe for merge.

**Review by adambasha0 — APPROVED** [review]
The issue is identified in the main branch, and the fix added solves the problem. Therefore it is safe to merge.

**Pull request merged**
