### PR TITLE
ElementDetails header refactor

### LINKED ISSUE #554: Exporting literature is not possible currently
The users are trying to export the DOI of the references added to the literature section of a sample into the spreadsheet. It would be great to have just one column there for that. Currently there is no way to link the literature to samples neither by exporting nor by creating a report.

### PR DESCRIPTION
**Pull request by CamAnNguyen**
- Refactor ElementDetails header (CSS and JS)
- Fix the UI bug in create Wellplate/Screen
- Add a tooltip on every button in the header (save, close, generateReport)
- Resolve #554

### CODE REVIEW

**Comment by Sergeykot** [comment]
I suggest to add 'tooltip' attribute on each button like this. just add 'tooltip'="save <name_of_item>'
so if user hover mouse there he/she sees the title

**Comment by Sergeykot** [comment]
update: it should be better like 'tooltip'="Save sample" or "Save wellplate"

**Comment by CamAnNguyen** [comment]
Good idea, will add a tooltip for this kind of button

**Comment by CamAnNguyen** [comment]
Code updated, I also update the Pull Request

**Comment by Sergeykot** [comment]
:+1:

**Pull request merged**
