### PR TITLE
Paging with search

### PR DESCRIPTION
**Pull request by CamAnNguyen**
- Fix paging bug while searching in both sort mode

### CODE REVIEW

**Comment by Sergeykot** [comment]
:+1:

**Comment by PiTrem** [comment]
:+1:

**Comment by Sergeykot** [comment]
I get an error when inut smth to a search field and presse `Enter` @CamAnNguyen 

search-error

**Comment by CamAnNguyen** [comment]
Thank you, I will check again

**Comment by PiTrem** [comment]
:+1:

**Comment by Sergeykot** [comment]
@CamAnNguyen please write a comment when you update a PR
also, seems to work. tested it :+1:

**Pull request merged**
